### ISSUE TITLE
Toolbar Toggle and Auto Dark Mode (time controlled)

### ISSUE THREAD

**Issue by deckerweb** [azizultex/Dark-Mode#154]
Hi there!
Congrats for getting the new ownership!

I just want to ask if you are open to add two - in my opinion - essential features:

1) Toolbar Toggle:
--> there was even a PR for it #144, but got closed some days ago, and I am really wondering why it was closed?
--> this toggle for enabling/disabling the whole thing is absolutely essential in my opionion, with it the plugin will make MUCH more sense and will become even more useful

2) Auto Dark Mode - time-based control:
Please re-add the auto dark mode setting that once was part of the plugin. I did never understand why it was taken out last year.
In my opinion it is essential to have a time-based control for enabling a dark mode - that is the reason why all OS that have dark mode, have such a function, and also a lot of mobile apps with dark mode allow for time-based control. There is no reason why this plugin here should not have it.

Adding both features to the core of the plugin (again) is the best way, as adding these "small" things in add-ons which makes not much sense to me.

Thanks a lot in advance!

**Comment by Presskopp** [comment]
I'm +1 for that.

It was deleted because:
https://github.com/dgwyer/Dark-Mode/wiki/Help:-Automatically-turning-Dark-Mode-on-or-off

**Comment by dgwyer** [comment]
Thanks for the kind words David! I hope I can do the plugin justice and build upon the excellent work Daniel has already done so far on this project.

As for adding in the two features you mentioned, I'm open to both of them in principle but there are other issues that I feel would be beneficial in being addressed first.

For now this one is key to how a dark mode should be implemented going forward - #155.

**Comment by deckerweb** [comment]
Since the owner changed again, can this issue/ feature please be reconsidered, @emrikol ? Thanks a lot in advance!
