### ISSUE TITLE
Add automatic dark mode based on prefers-color-scheme media query

### ISSUE THREAD

**Issue by mtttmpl** [azizultex/Dark-Mode#156]
A new media query standard and supported in Safari 12.1 allows for detections of the users preferred colour scheme.

https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

**Comment by dgwyer** [comment]
Firefox 67 now has this too with Chrome support coming later on in the year.

**Comment by andrewfitz** [comment]
I agree with this, please enable this query so it switches with the OS. Thank you for your work.
