### ISSUE TITLE
Interested to adopt the plugin

### ISSUE THREAD

**Issue by azizultex** [azizultex/Dark-Mode#173]
I recently came across your plugin Dark Mode on WordPress repository, and I really thought this is a great plugin. As it seems like the plugin is being abandoned, is it possible that I can adopt the plugin?

I saw the post on Tavern, and although it's a bit late to respond, I hope it's okay. Here is my WordPress.org profile https://profiles.wordpress.org/azizultex/

I have some enhancements planned and I'd be happy to take care of the plugin, and give support to the users.

Let me know what you think.

Thanks!
Azizul

**Comment by Greigh** [comment]
It does have a GNUv2 license. So I assume that's giving permission to fork it and such. It would be cool to have someone take this plugin up. I've been thinking about it, but with my schedule, I really don't have time.

I hope you're able to, @azizultex. Good luck my friend :)

**Comment by azizultex** [comment]
Thanks @Greigh 
Could you start the transfer of the WordPress.org plugin? My WordPress.org username is: azizultex 
I would go ahead and fork this repo and start adding new features as soon as possible.

Thanks for the opportunity.

**Comment by wiwi-websolutions** [comment]
@azizultex Are you still maintaining this plugin?

**Comment by lucanos** [comment]
> Dark Mode had not only changed owners, but it also had a new name and set of features unrelated to the plugin’s original promise. The plugin is now named WP Markdown Editor and bundles at least part of the commercially available Iceberg Editor plugin. It is also a limited version in which users are prompted to upgrade for the complete feature set.

[WPTavern: Dark Mode Plugin Repurposed and Renamed to WP Markdown Editor, Change Leaves Users Confused](https://wptavern.com/dark-mode-plugin-repurposed-and-renamed-to-wp-markdown-editor-change-leaves-users-confused)

**Comment by rekkisomo** [comment]
top 10 anime betrayals of all time
